API/urls.py
from django.conf.urls import url, include
from API.views import index, search, report_pdf, report_excel
from django.contrib.auth.decorators import login_required

app_name = 'API'
urlpatterns = [
    url(r'^index/$', index  , name="index"),
    url(r'^search/$', search  , name="search"),
    url(r'^report_pdf/$', login_required(report_pdf.as_view())  , name="report_pdf"),
    url(r'^report_excel/$', report_excel , name="report_excel"),
]

Biblioteca/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy

from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^book/', include('books.urls', namespace='books')),
    url(r'^API/', include('API.urls', namespace='API')),

    #Gestion de usuarios
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),

    #Logouut and Login
    url(r'^accounts/login/', LoginView.as_view(template_name='usuario/index.html'), name='login'),
    url(r'^$', LoginView.as_view(template_name='usuario/index.html'), name='login1'),
    url(r'^logout/', logout_then_login, name='logout'),

    #Restablecer contrasena
    url(r'^reset/password_reset', PasswordResetView.as_view(template_name='registro/password_reset_form.html', email_template_name='registro/password_reset_email.html', success_url=reverse_lazy('password_reset_done')), name='password_reset'),
    url(r'^/reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registro/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='registro/password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^reset/done', PasswordResetCompleteView.as_view(template_name='registro/password_reset_complete.html'),name='password_reset_complete'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.conf.urls import url, include
#from django.contrib import admin
#from django.urls import path
from usuario.views import registar_usuario,editar_usuario,eliminar_usuario
app_name = 'usuario'
urlpatterns = [
    url(r'^nuevo$',registar_usuario.as_view() , name="new"),
    url(r'^edit_book/(?P<pk>\d+)/$',editar_usuario.as_view() , name="edit"),
    url(r'^delete_book/(?P<pk>\d+)/$',eliminar_usuario.as_view() , name="delete"),
]

usuario/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

usuario/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class registroFormUser(UserCreationForm):
    class Meta:
        model = User 
        fields = [  
                    'username',
                    'first_name', 
                    'last_name',
                ]
        labels = {
                    'username': 'Usuario',
                    'first_name': 'Nombre',
                    'last_name': 'Apellido',
        }

usuario/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.views.generic import ListView,UpdateView, DeleteView,CreateView
from django.urls import reverse_lazy
from usuario.forms import registroFormUser

class registar_usuario(CreateView):
    model = User
    template_name = "usuario/registrar.html"
    form_class = registroFormUser
    success_url = reverse_lazy("login")

class eliminar_usuario(DeleteView):
    model = User
    template_name = 'usuario/eliminar.html'
    success_url = reverse_lazy('login')

class editar_usuario(UpdateView):
    model = User
    form_class = registroFormUser
    template_name = 'usuario/edit.html'
    success_url = reverse_lazy('books:list_book')
    

templates/usuario/edit.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %} 
<div class="container">
  <form  method="post" >
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Guardar" />
  </form> 
</div>
{% endblock %}

templates/usuario/eliminar.html
{% extends 'base/base.html' %}

{% block header %}

{% endblock %}

{% block content %} 
<form method="POST">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de "{{books.title}}"?</h3>

    <button class='btn btn-danger' type="submit">Si, eliminar</button>
    <a class='btn btn-default' href="{% url 'login' %}">Cancelar</a>
</form>

{% endblock %}

templates/usuario/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block header %}
<div class="fixed-top">
	<nav class="navbar navbar-expand-lg navbar-light bg-light bg-dark ">
    	<a class=" text-white navbar-brand" href="{% url 'login1' %}">Libreria</a>
  	</nav>
</div>
{% endblock %}

{% block enlaces %}

   <!--Made with love by Mutiullah Samim -->
   
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
{% endblock %}


{% block content %} 
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Iniciar sesión</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div>
			</div>
			<div class="card-body">
				<form method="POST">
                    {% csrf_token %}
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" class="form-control" placeholder="Nombre de usuario" name="username">
						
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" class="form-control" placeholder="Contraseña" name="password">
					</div>
					
					<div class="form-group">
						<input type="submit" value="Ingresar" class="login_btn btn float-right ">
					</div>
					{% if form.errors %}
					<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong">
						Ver errores
					</button>
					{% endif %}
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					¿No tienes cuenta?<a href="{% url 'usuario:new' %}">Crea una cuenta!</a>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Button trigger modal -->
  <!-- Modal -->
  <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
	<div class="modal-dialog" role="document">
	  <div class="modal-content">
		<div class="modal-header">
		  <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
		  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		  </button>
		</div>
		<div class="modal-body">
			{{ form.errors }}
		</div>
		<div class="modal-footer">
		  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		</div>
	  </div>
	</div>
  </div>

{% endblock %}

templates/usuario/registrar.html
{% extends 'base/base.html' %}
{% load static %}
{% block enlaces %}
	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
{% endblock %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-light bg-dark ">
    <a class=" text-white navbar-brand" href="{% url 'login1' %}">App Granja</a>
    
</nav>
{% endblock %}
{% block content %} 
<h1 class="text-center">Formulario de registro</h1>
<div class="container opacity">
    <div class="d-flex justify-content-center h-100">
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="id_first_name">{{ form.first_name.label }}</label>
                        <input class="form-control" type="text" name="first_name" maxlength="30" id="id_first_name">
                        <span class="helptext">{{ form.first_name.help_text }}</span>
                        <span class="helptext">{{ form.first_name.errors }}</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 ">
                    <div class="form-group">
                        <label for="id_last_name">{{ form.last_name.label }}</label>
                        <input class="form-control" type="text" name="last_name" maxlength="30" id="id_last_name">
                        <span class="helptext">{{ form.last_name.help_text }}</span>
                        <span class="helptext">{{ form.last_name.errors }}</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 ">
                    <div class="form-group">
                        <label for="id_username">{{ form.username.label }}</label>
                        <input class="form-control" type="text" name="username" maxlength="30" id="id_username">
                        <span class="helptext">{{ form.username.help_text }}</span>
                        <span class="helptext">{{ form.username.errors }}</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 ">
                    <div class="form-group">
                        <label for="id_password1">{{ form.password1.label }}</label>
                        <input class="form-control" type="password" name="password1" maxlength="30" id="id_password1">
                        <span class="helptext">{{ form.password1.helps }}</span>
                        <span class="helptext">{{ form.password1.errors }}</span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 ">
                    <div class="form-group">
                        <label for="id_password2">Reescriba su contraseña</label>
                        <input class="form-control" type="password" name="password2" maxlength="30" id="id_password2">
                        <span class="helptext">{{ form.password2.help_text }}</span>
                        <span class="helptext">{{ form.password2.errors }}</span>
                    </div>
                </div>
            </div>
            <button class="btn btn-warning center" type="submit">Guardar</button>
        </form>
    </div>
</div>


{% endblock %}