API/urls.py
from django.conf.urls import url, include
from API.views import index, search, report_pdf, report_excel
from django.contrib.auth.decorators import login_required

app_name = 'API'
urlpatterns = [
    url(r'^index/$', index  , name="index"),
    url(r'^search/$', search  , name="search"),
    url(r'^report_pdf/$', login_required(report_pdf.as_view())  , name="report_pdf"),
    url(r'^report_excel/$', report_excel , name="report_excel"),
]

Biblioteca/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy

from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^book/', include('books.urls', namespace='books')),
    url(r'^API/', include('API.urls', namespace='API')),

    #Gestion de usuarios
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),

    #Logouut and Login
    url(r'^accounts/login/', LoginView.as_view(template_name='usuario/index.html'), name='login'),
    url(r'^$', LoginView.as_view(template_name='usuario/index.html'), name='login1'),
    url(r'^logout/', logout_then_login, name='logout'),

    #Restablecer contrasena
    url(r'^reset/password_reset', PasswordResetView.as_view(template_name='registro/password_reset_form.html', email_template_name='registro/password_reset_email.html', success_url=reverse_lazy('password_reset_done')), name='password_reset'),
    url(r'^/reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registro/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='registro/password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^reset/done', PasswordResetCompleteView.as_view(template_name='registro/password_reset_complete.html'),name='password_reset_complete'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.conf.urls import url, include
from books.views import *
from django.contrib.auth.decorators import login_required

app_name = 'books'
urlpatterns = [
    #book
    url(r'^listar_book$', login_required(book_list.as_view() ), name='list_book'),
    url(r'^new_book$', book_new , name='new_book'),
    url(r'^delete_book/(?P<pk>\d+)/$', login_required(book_delete.as_view()) , name='delete_book'),
    url(r'^edit_book/(?P<pk>\d+)/$', login_required(book_edit.as_view()) , name='edit_book'),

    #Comentarios
    url(r'^listar_comments/(?P<id_book>\d+)/$', comments_list , name='list_comments'),
    url(r'^new_comments/(?P<id_book>\d+)/$', comments_new , name='new_comments'),
    url(r'^delete_comments/(?P<id_book>\d+)/(?P<id_comment>\d+)/$', comments_delete , name='delete_comments'),
    url(r'^edit_comments/(?P<id_book>\d+)/(?P<id_comment>\d+)/$', comments_edit , name='edit_comments'),
    ] 

usuario/urls.py
from django.conf.urls import url, include
#from django.contrib import admin
#from django.urls import path
from usuario.views import registar_usuario,editar_usuario,eliminar_usuario
app_name = 'usuario'
urlpatterns = [
    url(r'^nuevo$',registar_usuario.as_view() , name="new"),
    url(r'^edit_book/(?P<pk>\d+)/$',editar_usuario.as_view() , name="edit"),
    url(r'^delete_book/(?P<pk>\d+)/$',eliminar_usuario.as_view() , name="delete"),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block tittle %} Biblioteca {% endblock %}</title>
    {% block enlaces %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    {% block extrahead %}
    {% endblock %}

    {% block header %}
    {% include 'base/header.html' %}
    {% endblock %}
    
    {% block content %}
    <h1>este es el bloque del contenido</h1>
    {% endblock %}

    {% block footer %}

    {% endblock %}

    {% block extrajs %}
    {% endblock %}
<script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/index.js' %}"></script>

</body>
</html>

templates/base/footer.html
<div class="fixed-bottom">
  <div class="bottom">
    <!-- Footer -->
    <footer class="page-footer font-small blue pt-4">

      <!-- Footer Links -->
      <div class="bg-secondary text-white container-fluid text-center text-md-left">

        <!-- Grid row -->
        <div class="row">

          <!-- Grid column -->
          <div class="col-md-6 mt-md-0 mt-3">

            <!-- Content -->
            <h5 class="text-uppercase">Libros</h5>
            <p>Esta es una increible herramienta para administrar los comentarios de los libros registrados.</p>

          </div>
          <!-- Grid column -->

          <hr class="clearfix w-100 d-md-none pb-3">

          <!-- Grid column -->
          <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="text-uppercase">Desarrollador</h5>

            <ul class="list-unstyled">
              <li>
                <a style='text-decoration:none;color:white;' href="https://github.com/JorgeluissilvaC">Jorge Luis Silva Correa</a>
              </li>
            </ul>

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="text-uppercase">Correo</h5>

            <ul class="list-unstyled">
              <li>
                <a>jlsilva@uninorte.edu.co</a>
              </li>

            </ul>

          </div>
          <!-- Grid column -->

        </div>
        <!-- Grid row -->

      </div>
      <!-- Footer Links -->

      <!-- Copyright -->
      <div class="footer-copyright text-center py-3 bg-dark text-white">© 2020 Desarrollado en Bogotá, Colombia
        <a href="#"></a>
      </div>
      <!-- Copyright -->

    </footer>
    <!-- Footer -->

  </div>
</div>

templates/base/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'books:list_book' %}">Biblioteca</a>  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item active">
          <a class="nav-link" href="{% url 'API:index' %}">OpenLibra (API) <span class="sr-only">(current)</span></a>
        </li>

        
      </ul>
      <div class="dropdown">
        <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Libros 
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <a class="dropdown-item" href="{% url 'books:list_book' %}">Lista de libros</a>
          <a class="dropdown-item" href="{% url 'books:new_book' %}">Agregar un libro</a>
        </div>
      </div>

      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Bienvenido {{ request.user.first_name  }} {{request.user.last_name }}, ({{request.user.username}})
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="{% url 'usuario:edit' request.user.id %}">Editar Usuario</a>
          <a class="dropdown-item" href="{% url 'usuario:delete' request.user.id %}">Eliminar Usuario</a>
        </div>
      </div>
      <a class="btn btn-danger" class="nav-link" href="{% url 'logout' %}" >Cerrar sesión <span class="sr-only">(current)</span></a>
    </div>
  </nav>