API/urls.py
from django.conf.urls import url, include
from API.views import index, search, report_pdf, report_excel
from django.contrib.auth.decorators import login_required

app_name = 'API'
urlpatterns = [
    url(r'^index/$', index  , name="index"),
    url(r'^search/$', search  , name="search"),
    url(r'^report_pdf/$', login_required(report_pdf.as_view())  , name="report_pdf"),
    url(r'^report_excel/$', report_excel , name="report_excel"),
]

Biblioteca/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy

from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^book/', include('books.urls', namespace='books')),
    url(r'^API/', include('API.urls', namespace='API')),

    #Gestion de usuarios
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),

    #Logouut and Login
    url(r'^accounts/login/', LoginView.as_view(template_name='usuario/index.html'), name='login'),
    url(r'^$', LoginView.as_view(template_name='usuario/index.html'), name='login1'),
    url(r'^logout/', logout_then_login, name='logout'),

    #Restablecer contrasena
    url(r'^reset/password_reset', PasswordResetView.as_view(template_name='registro/password_reset_form.html', email_template_name='registro/password_reset_email.html', success_url=reverse_lazy('password_reset_done')), name='password_reset'),
    url(r'^/reset/password_reset_done', PasswordResetDoneView.as_view(template_name='registro/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='registro/password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^reset/done', PasswordResetCompleteView.as_view(template_name='registro/password_reset_complete.html'),name='password_reset_complete'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/urls.py
from django.conf.urls import url, include
from books.views import *
from django.contrib.auth.decorators import login_required

app_name = 'books'
urlpatterns = [
    #book
    url(r'^listar_book$', login_required(book_list.as_view() ), name='list_book'),
    url(r'^new_book$', book_new , name='new_book'),
    url(r'^delete_book/(?P<pk>\d+)/$', login_required(book_delete.as_view()) , name='delete_book'),
    url(r'^edit_book/(?P<pk>\d+)/$', login_required(book_edit.as_view()) , name='edit_book'),

    #Comentarios
    url(r'^listar_comments/(?P<id_book>\d+)/$', comments_list , name='list_comments'),
    url(r'^new_comments/(?P<id_book>\d+)/$', comments_new , name='new_comments'),
    url(r'^delete_comments/(?P<id_book>\d+)/(?P<id_comment>\d+)/$', comments_delete , name='delete_comments'),
    url(r'^edit_comments/(?P<id_book>\d+)/(?P<id_comment>\d+)/$', comments_edit , name='edit_comments'),
    ] 

templates/comments/comment_delete.html
{% extends 'base/base.html' %}

{% block header %}

{% endblock %}

{% block content %} 
<form method="POST">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de "{{comments.text}}"?</h3>

    <button class='btn btn-danger' type="submit">Si, eliminar</button>
    <a class='btn btn-default' href="{% url 'books:list_book' %}">Cancelar</a>
</form>

{% endblock %}

templates/comments/comment_list.html
{% extends 'base/base.html' %}

{% block content %} 
<div class="container">
    <div class="row">
        <div class="col-12 ">
            {% if book %}
            <h2> {{ book.title }}</h2>
            <h4>{{ book.publication_date }}</h4>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <!--Agregar un comentario -->
        <div class="col-12 ">
            <div class="m-1 center">
                <a href="{% url 'books:new_comments' book.id %}" class="btn btn-success ">Agregar un comentario</a>
            </div>
        </div>
    </div>
    <div class="row">
        <!--Buscador de animales-->
        <div class="col-12">

        </div>
    </div>
    <div class="row">
        <!--Lista de Animales -->
        <div class="col-12">
            {% if comentarios %}
                <ul class="list-group list-group-flush">
                    {% for comment in comentarios %}
                        <li class="list-group-item">
                          <p><b>Comentario</b>: {{comment.text}}</p> 
                          <p><b>Usuario</b>: {{comment.id_user.username}} </p> 
                          <p><b>Nombre</b>: {{comment.id_user.first_name}} {{comment.id_user.last_name}}</p> 
                          <p><b>Fecha de creación</b>: {{comment.created_date}} </p> 
                          <a class="btn btn-primary" href="{% url 'books:edit_comments'  book.id comment.id %}">Editar</a>
                          <a class="btn btn-danger" href="{% url 'books:delete_comments' book.id comment.id %}">Eliminar</a>
                        </li>
                    {% endfor %}
                </ul>
                {% else %}
                <h1> No se encontraron Comentario registrados</h1>
                {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/comments/comment_new.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %} 
<div class="container">
  <form  method="post" >
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Guardar" />
  </form> 
</div>
{% endblock %}